main: main.c Text/text.c Tree/tree.c Differ/differ.c
	gcc -o main	main.c Text/text.c Tree/tree.c Differ/differ.c -lm

# calc: main.c Text/text.c Tree/tree.c Differ/differ.c AnalExpr/calc.c
# 	gcc -o main	main.c Text/text.c Tree/tree.c Differ/differ.c AnalExpr/calc.c -lm